import { supabase } from './supabaseClient.js';

// Helper to build a question object
function q(topic: string, diff: string, vi: string, en: string, choices: string[], correct: number) {
    return {
        subject: 'english',
        topic,
        difficulty: diff,
        content: {
            vi: { questionText: vi, questionReadText: vi },
            en: { questionText: en, questionReadText: en },
        },
        choices: choices.map((v, i) => ({ id: i + 1, value: v, label: String.fromCharCode(65 + i) })),
        correct_answer_id: correct,
    };
}

// 500 English Questions - Grade 2
// Source: 500_English_Questions_Grade2.xlsx
export const grade2EnglishQuestions = [

    // ── Animals ──
    q('Animals', 'easy', 'What sound does a dog make?', 'What sound does a dog make?', ['Woof', 'Moo', 'Meow', 'Quack'], 1),
    q('Animals', 'easy', 'What sound does a cat make?', 'What sound does a cat make?', ['Woof', 'Meow', 'Moo', 'Oink'], 2),
    q('Animals', 'easy', 'What sound does a cow make?', 'What sound does a cow make?', ['Moo', 'Quack', 'Baa', 'Roar'], 1),
    q('Animals', 'easy', 'What sound does a duck make?', 'What sound does a duck make?', ['Bark', 'Moo', 'Quack', 'Hiss'], 3),
    q('Animals', 'easy', 'What sound does a lion make?', 'What sound does a lion make?', ['Roar', 'Tweet', 'Hiss', 'Squeak'], 1),
    q('Animals', 'easy', 'Which animal has a long neck?', 'Which animal has a long neck?', ['Elephant', 'Giraffe', 'Hippo', 'Bear'], 2),
    q('Animals', 'easy', 'Which animal has a trunk?', 'Which animal has a trunk?', ['Lion', 'Tiger', 'Elephant', 'Horse'], 3),
    q('Animals', 'easy', 'Which animal lives in water?', 'Which animal lives in water?', ['Dog', 'Cat', 'Fish', 'Rabbit'], 3),
    q('Animals', 'easy', 'Which animal can fly?', 'Which animal can fly?', ['Dog', 'Cat', 'Bird', 'Fish'], 3),
    q('Animals', 'easy', 'Which animal has stripes?', 'Which animal has stripes?', ['Lion', 'Tiger', 'Elephant', 'Bear'], 2),
    q('Animals', 'easy', 'What do bees make?', 'What do bees make?', ['Milk', 'Honey', 'Juice', 'Butter'], 2),
    q('Animals', 'easy', 'Which animal is the king of the jungle?', 'Which animal is the king of the jungle?', ['Tiger', 'Bear', 'Lion', 'Wolf'], 3),
    q('Animals', 'easy', 'Which animal hops?', 'Which animal hops?', ['Rabbit', 'Dog', 'Fish', 'Cat'], 1),
    q('Animals', 'easy', 'Which animal has a shell?', 'Which animal has a shell?', ['Dog', 'Turtle', 'Horse', 'Cat'], 2),
    q('Animals', 'easy', 'Which animal gives us milk?', 'Which animal gives us milk?', ['Dog', 'Cat', 'Cow', 'Pig'], 3),
    q('Animals', 'easy', 'Which animal says \'Baa\'?', 'Which animal says \'Baa\'?', ['Dog', 'Cow', 'Sheep', 'Duck'], 3),
    q('Animals', 'easy', 'Which animal has feathers?', 'Which animal has feathers?', ['Dog', 'Cat', 'Bird', 'Fish'], 3),
    q('Animals', 'easy', 'Which animal is very big and grey?', 'Which animal is very big and grey?', ['Cat', 'Rabbit', 'Elephant', 'Fox'], 3),
    q('Animals', 'easy', 'What color is a flamingo?', 'What color is a flamingo?', ['Blue', 'Green', 'Pink', 'Yellow'], 3),
    q('Animals', 'easy', 'Which animal sleeps in winter?', 'Which animal sleeps in winter?', ['Dog', 'Bear', 'Cat', 'Fish'], 2),
    q('Animals', 'easy', 'Which animal has eight legs?', 'Which animal has eight legs?', ['Butterfly', 'Spider', 'Bee', 'Ant'], 2),
    q('Animals', 'easy', 'Which animal has a bushy tail?', 'Which animal has a bushy tail?', ['Squirrel', 'Dog', 'Fish', 'Duck'], 1),
    q('Animals', 'easy', 'What is a baby cat called?', 'What is a baby cat called?', ['Puppy', 'Kitten', 'Cub', 'Chick'], 2),
    q('Animals', 'easy', 'What is a baby dog called?', 'What is a baby dog called?', ['Kitten', 'Cub', 'Puppy', 'Foal'], 3),
    q('Animals', 'easy', 'What is a baby chicken called?', 'What is a baby chicken called?', ['Puppy', 'Kitten', 'Chick', 'Cub'], 3),
    q('Animals', 'easy', 'Which animal lives in a nest?', 'Which animal lives in a nest?', ['Dog', 'Fish', 'Cat', 'Bird'], 4),
    q('Animals', 'easy', 'Which animal has a very long tongue?', 'Which animal has a very long tongue?', ['Dog', 'Giraffe', 'Cat', 'Rabbit'], 2),
    q('Animals', 'easy', 'What do pandas eat?', 'What do pandas eat?', ['Meat', 'Bamboo', 'Fish', 'Grass'], 2),
    q('Animals', 'easy', 'Which animal is black and white?', 'Which animal is black and white?', ['Lion', 'Zebra', 'Bear', 'Wolf'], 2),
    q('Animals', 'easy', 'Which animal is the fastest on land?', 'Which animal is the fastest on land?', ['Lion', 'Horse', 'Cheetah', 'Tiger'], 3),
    q('Animals', 'easy', 'Which animal can swim and walk on land?', 'Which animal can swim and walk on land?', ['Dog', 'Cat', 'Frog', 'Bird'], 3),
    q('Animals', 'easy', 'What is a group of fish called?', 'What is a group of fish called?', ['Herd', 'Flock', 'School', 'Pack'], 3),
    q('Animals', 'easy', 'Which animal has spots?', 'Which animal has spots?', ['Tiger', 'Leopard', 'Lion', 'Bear'], 2),
    q('Animals', 'easy', 'Which animal can change color?', 'Which animal can change color?', ['Dog', 'Chameleon', 'Cat', 'Fish'], 2),
    q('Animals', 'easy', 'Which animal builds dams in rivers?', 'Which animal builds dams in rivers?', ['Fish', 'Duck', 'Beaver', 'Frog'], 3),
    q('Animals', 'easy', 'What do frogs eat?', 'What do frogs eat?', ['Grass', 'Insects', 'Seeds', 'Fish'], 2),
    q('Animals', 'easy', 'Which is the largest animal on land?', 'Which is the largest animal on land?', ['Hippo', 'Giraffe', 'Elephant', 'Rhino'], 3),
    q('Animals', 'easy', 'Which animal has a pouch?', 'Which animal has a pouch?', ['Dog', 'Kangaroo', 'Cat', 'Bear'], 2),
    q('Animals', 'easy', 'Which animal can talk like humans?', 'Which animal can talk like humans?', ['Crow', 'Parrot', 'Eagle', 'Owl'], 2),
    q('Animals', 'easy', 'Which animal is known for being wise?', 'Which animal is known for being wise?', ['Eagle', 'Parrot', 'Owl', 'Crow'], 3),
    q('Animals', 'easy', 'What do horses eat?', 'What do horses eat?', ['Meat', 'Fish', 'Hay and grass', 'Insects'], 3),
    q('Animals', 'easy', 'Which animal has a very long nose?', 'Which animal has a very long nose?', ['Giraffe', 'Elephant', 'Hippo', 'Rhino'], 2),
    q('Animals', 'easy', 'Which bird cannot fly?', 'Which bird cannot fly?', ['Eagle', 'Pigeon', 'Penguin', 'Sparrow'], 3),
    q('Animals', 'easy', 'Which animal has a hump?', 'Which animal has a hump?', ['Horse', 'Camel', 'Donkey', 'Cow'], 2),
    q('Animals', 'easy', 'Which animal is known as man\'s best friend?', 'Which animal is known as man\'s best friend?', ['Cat', 'Dog', 'Rabbit', 'Horse'], 2),
    q('Animals', 'easy', 'What is a baby cow called?', 'What is a baby cow called?', ['Kitten', 'Puppy', 'Calf', 'Foal'], 3),
    q('Animals', 'easy', 'Which animal produces silk?', 'Which animal produces silk?', ['Bee', 'Ant', 'Silkworm', 'Spider'], 3),
    q('Animals', 'easy', 'Which animal eats only plants?', 'Which animal eats only plants?', ['Lion', 'Tiger', 'Rabbit', 'Wolf'], 3),
    q('Animals', 'easy', 'What is a baby sheep called?', 'What is a baby sheep called?', ['Cub', 'Kitten', 'Lamb', 'Calf'], 3),
    q('Animals', 'easy', 'Which animal has the longest lifespan?', 'Which animal has the longest lifespan?', ['Dog', 'Cat', 'Tortoise', 'Elephant'], 3),

    // ── Colors & Shapes ──
    q('Colors & Shapes', 'easy', 'What color is the sun?', 'What color is the sun?', ['Blue', 'Yellow', 'Green', 'Red'], 2),
    q('Colors & Shapes', 'easy', 'What color is grass?', 'What color is grass?', ['Blue', 'Yellow', 'Green', 'Red'], 3),
    q('Colors & Shapes', 'easy', 'What color is the sky?', 'What color is the sky?', ['Blue', 'Yellow', 'Green', 'Red'], 1),
    q('Colors & Shapes', 'easy', 'What color is a banana?', 'What color is a banana?', ['Red', 'Blue', 'Yellow', 'Green'], 3),
    q('Colors & Shapes', 'easy', 'What color is a tomato?', 'What color is a tomato?', ['Blue', 'Red', 'Green', 'Yellow'], 2),
    q('Colors & Shapes', 'easy', 'What color is snow?', 'What color is snow?', ['Blue', 'White', 'Yellow', 'Grey'], 2),
    q('Colors & Shapes', 'easy', 'What color is coal?', 'What color is coal?', ['White', 'Grey', 'Black', 'Blue'], 3),
    q('Colors & Shapes', 'easy', 'What color is a pumpkin?', 'What color is a pumpkin?', ['Red', 'Blue', 'Green', 'Orange'], 4),
    q('Colors & Shapes', 'easy', 'What color is a grape?', 'What color is a grape?', ['Orange', 'Yellow', 'Purple', 'Red'], 3),
    q('Colors & Shapes', 'easy', 'What color is a strawberry?', 'What color is a strawberry?', ['Blue', 'Red', 'Yellow', 'Green'], 2),
    q('Colors & Shapes', 'easy', 'How many sides does a triangle have?', 'How many sides does a triangle have?', ['2', '3', '4', '5'], 2),
    q('Colors & Shapes', 'easy', 'How many sides does a square have?', 'How many sides does a square have?', ['3', '2', '4', '6'], 3),
    q('Colors & Shapes', 'easy', 'How many sides does a circle have?', 'How many sides does a circle have?', ['1', '0', '2', '4'], 2),
    q('Colors & Shapes', 'easy', 'How many sides does a rectangle have?', 'How many sides does a rectangle have?', ['3', '5', '4', '6'], 3),
    q('Colors & Shapes', 'easy', 'Which shape has all equal sides?', 'Which shape has all equal sides?', ['Rectangle', 'Square', 'Triangle', 'Circle'], 2),
    q('Colors & Shapes', 'easy', 'What shape is a pizza?', 'What shape is a pizza?', ['Square', 'Triangle', 'Circle', 'Rectangle'], 3),
    q('Colors & Shapes', 'easy', 'What shape is a book?', 'What shape is a book?', ['Circle', 'Triangle', 'Rectangle', 'Pentagon'], 3),
    q('Colors & Shapes', 'easy', 'What shape is a clock?', 'What shape is a clock?', ['Square', 'Circle', 'Triangle', 'Rectangle'], 2),
    q('Colors & Shapes', 'easy', 'What color is an orange?', 'What color is an orange?', ['Red', 'Yellow', 'Orange', 'Green'], 3),
    q('Colors & Shapes', 'easy', 'What color is a lemon?', 'What color is a lemon?', ['Orange', 'Yellow', 'Green', 'Red'], 2),
    q('Colors & Shapes', 'easy', 'What color is a carrot?', 'What color is a carrot?', ['Blue', 'Green', 'Orange', 'Red'], 3),
    q('Colors & Shapes', 'easy', 'What color is the ocean?', 'What color is the ocean?', ['Green', 'Blue', 'Yellow', 'Red'], 2),
    q('Colors & Shapes', 'easy', 'What color is a rose?', 'What color is a rose?', ['Blue', 'Green', 'Red', 'Yellow'], 3),
    q('Colors & Shapes', 'easy', 'What is the color of night?', 'What is the color of night?', ['White', 'Yellow', 'Black', 'Green'], 3),
    q('Colors & Shapes', 'easy', 'What color are leaves in spring?', 'What color are leaves in spring?', ['Yellow', 'Red', 'Green', 'Brown'], 3),
    q('Colors & Shapes', 'easy', 'What color are leaves in autumn?', 'What color are leaves in autumn?', ['Green', 'Orange and red', 'Blue', 'Purple'], 2),
    q('Colors & Shapes', 'easy', 'Which color is NOT in the rainbow?', 'Which color is NOT in the rainbow?', ['Red', 'Pink', 'Orange', 'Yellow'], 2),
    q('Colors & Shapes', 'easy', 'How many colors are in the rainbow?', 'How many colors are in the rainbow?', ['5', '6', '7', '8'], 3),
    q('Colors & Shapes', 'easy', 'What color is chocolate?', 'What color is chocolate?', ['White', 'Yellow', 'Brown', 'Orange'], 3),
    q('Colors & Shapes', 'easy', 'What color is the moon?', 'What color is the moon?', ['Orange', 'White or grey', 'Blue', 'Green'], 2),

    // ── Food & Drinks ──
    q('Food & Drinks', 'easy', 'Which fruit is yellow and curved?', 'Which fruit is yellow and curved?', ['Apple', 'Orange', 'Banana', 'Grape'], 3),
    q('Food & Drinks', 'easy', 'Which fruit is red and round?', 'Which fruit is red and round?', ['Banana', 'Apple', 'Mango', 'Grape'], 2),
    q('Food & Drinks', 'easy', 'Which vegetable is orange?', 'Which vegetable is orange?', ['Potato', 'Tomato', 'Carrot', 'Onion'], 3),
    q('Food & Drinks', 'easy', 'What drink comes from cows?', 'What drink comes from cows?', ['Juice', 'Water', 'Milk', 'Tea'], 3),
    q('Food & Drinks', 'easy', 'What do bees make that is sweet?', 'What do bees make that is sweet?', ['Jam', 'Honey', 'Sugar', 'Butter'], 2),
    q('Food & Drinks', 'easy', 'What is the main ingredient in bread?', 'What is the main ingredient in bread?', ['Rice', 'Flour', 'Corn', 'Oats'], 2),
    q('Food & Drinks', 'easy', 'Which food comes from hens?', 'Which food comes from hens?', ['Milk', 'Cheese', 'Eggs', 'Butter'], 3),
    q('Food & Drinks', 'easy', 'What is spaghetti made from?', 'What is spaghetti made from?', ['Rice', 'Potato', 'Pasta', 'Bread'], 3),
    q('Food & Drinks', 'easy', 'Which of these is a vegetable?', 'Which of these is a vegetable?', ['Apple', 'Banana', 'Carrot', 'Mango'], 3),
    q('Food & Drinks', 'easy', 'Which of these is a fruit?', 'Which of these is a fruit?', ['Carrot', 'Onion', 'Apple', 'Potato'], 3),
    q('Food & Drinks', 'easy', 'What flavor is lemon?', 'What flavor is lemon?', ['Sweet', 'Sour', 'Salty', 'Bitter'], 2),
    q('Food & Drinks', 'easy', 'What flavor is sugar?', 'What flavor is sugar?', ['Sour', 'Salty', 'Sweet', 'Spicy'], 3),
    q('Food & Drinks', 'easy', 'What do we put on salads?', 'What do we put on salads?', ['Jam', 'Dressing', 'Syrup', 'Honey'], 2),
    q('Food & Drinks', 'easy', 'Which food is made from milk?', 'Which food is made from milk?', ['Bread', 'Jam', 'Cheese', 'Pasta'], 3),
    q('Food & Drinks', 'easy', 'What do we call morning meal?', 'What do we call morning meal?', ['Dinner', 'Lunch', 'Breakfast', 'Snack'], 3),
    q('Food & Drinks', 'easy', 'What do we call midday meal?', 'What do we call midday meal?', ['Breakfast', 'Lunch', 'Dinner', 'Supper'], 2),
    q('Food & Drinks', 'easy', 'What do we call evening meal?', 'What do we call evening meal?', ['Breakfast', 'Snack', 'Lunch', 'Dinner'], 4),
    q('Food & Drinks', 'easy', 'Which fruit has seeds inside?', 'Which fruit has seeds inside?', ['All fruits', 'Banana', 'Mango', 'Watermelon'], 1),
    q('Food & Drinks', 'easy', 'What is the color of an unripe banana?', 'What is the color of an unripe banana?', ['Yellow', 'Red', 'Green', 'Orange'], 3),
    q('Food & Drinks', 'easy', 'Which food is crunchy?', 'Which food is crunchy?', ['Banana', 'Mango', 'Chips', 'Milk'], 3),
    q('Food & Drinks', 'easy', 'What do we put in a sandwich?', 'What do we put in a sandwich?', ['Filling', 'Jam only', 'Water', 'Milk'], 1),
    q('Food & Drinks', 'easy', 'What is orange juice made from?', 'What is orange juice made from?', ['Apples', 'Grapes', 'Oranges', 'Lemons'], 3),
    q('Food & Drinks', 'easy', 'Which food is spicy?', 'Which food is spicy?', ['Ice cream', 'Chili pepper', 'Banana', 'Milk'], 2),
    q('Food & Drinks', 'easy', 'What is ice cream made from?', 'What is ice cream made from?', ['Juice', 'Milk and cream', 'Water', 'Tea'], 2),
    q('Food & Drinks', 'easy', 'What do we eat soup with?', 'What do we eat soup with?', ['Fork', 'Spoon', 'Chopsticks', 'Hands'], 2),
    q('Food & Drinks', 'easy', 'What is pizza topped with?', 'What is pizza topped with?', ['Sauce and cheese', 'Jam', 'Butter', 'Sugar'], 1),
    q('Food & Drinks', 'easy', 'Which drink is hot?', 'Which drink is hot?', ['Juice', 'Milk', 'Tea', 'Soda'], 3),
    q('Food & Drinks', 'easy', 'Which food grows underground?', 'Which food grows underground?', ['Apple', 'Banana', 'Potato', 'Mango'], 3),
    q('Food & Drinks', 'easy', 'What is a salad mainly made of?', 'What is a salad mainly made of?', ['Meat', 'Vegetables', 'Bread', 'Fruit'], 2),
    q('Food & Drinks', 'easy', 'Which of these is a dairy product?', 'Which of these is a dairy product?', ['Juice', 'Yogurt', 'Bread', 'Soda'], 2),
    q('Food & Drinks', 'easy', 'What do we use to cut food?', 'What do we use to cut food?', ['Spoon', 'Fork', 'Knife', 'Plate'], 3),
    q('Food & Drinks', 'easy', 'Which food is sweet and frozen?', 'Which food is sweet and frozen?', ['Pizza', 'Soup', 'Ice cream', 'Bread'], 3),
    q('Food & Drinks', 'easy', 'What is popcorn made from?', 'What is popcorn made from?', ['Wheat', 'Rice', 'Corn', 'Oats'], 3),
    q('Food & Drinks', 'easy', 'Which meal do people eat last?', 'Which meal do people eat last?', ['Breakfast', 'Lunch', 'Dinner', 'Snack'], 3),
    q('Food & Drinks', 'easy', 'What flavor is vinegar?', 'What flavor is vinegar?', ['Sweet', 'Sour', 'Salty', 'Spicy'], 2),
    q('Food & Drinks', 'easy', 'Which fruit is purple?', 'Which fruit is purple?', ['Banana', 'Orange', 'Grape', 'Mango'], 3),
    q('Food & Drinks', 'easy', 'What is butter made from?', 'What is butter made from?', ['Juice', 'Cream', 'Water', 'Flour'], 2),
    q('Food & Drinks', 'easy', 'Which of these is a grain?', 'Which of these is a grain?', ['Carrot', 'Apple', 'Rice', 'Milk'], 3),
    q('Food & Drinks', 'easy', 'What do we call a meal between lunch and dinner?', 'What do we call a meal between lunch and dinner?', ['Breakfast', 'Brunch', 'Snack', 'Supper'], 3),
    q('Food & Drinks', 'easy', 'Which fruit has a hard yellow skin?', 'Which fruit has a hard yellow skin?', ['Apple', 'Pineapple', 'Grape', 'Cherry'], 2),

    // ── Body Parts ──
    q('Body Parts', 'easy', 'How many fingers do we have on both hands?', 'How many fingers do we have on both hands?', ['8', '9', '10', '12'], 3),
    q('Body Parts', 'easy', 'Which body part do we use to smell?', 'Which body part do we use to smell?', ['Eyes', 'Ears', 'Nose', 'Mouth'], 3),
    q('Body Parts', 'easy', 'Which body part do we use to hear?', 'Which body part do we use to hear?', ['Eyes', 'Ears', 'Nose', 'Mouth'], 2),
    q('Body Parts', 'easy', 'Which body part do we use to see?', 'Which body part do we use to see?', ['Eyes', 'Ears', 'Nose', 'Mouth'], 1),
    q('Body Parts', 'easy', 'Which body part do we use to taste?', 'Which body part do we use to taste?', ['Eyes', 'Ears', 'Nose', 'Tongue'], 4),
    q('Body Parts', 'easy', 'How many toes do we have?', 'How many toes do we have?', ['8', '9', '10', '12'], 3),
    q('Body Parts', 'easy', 'What do we use to breathe?', 'What do we use to breathe?', ['Stomach', 'Lungs', 'Heart', 'Brain'], 2),
    q('Body Parts', 'easy', 'What do we use to think?', 'What do we use to think?', ['Heart', 'Stomach', 'Brain', 'Lungs'], 3),
    q('Body Parts', 'easy', 'How many eyes do humans have?', 'How many eyes do humans have?', ['1', '2', '3', '4'], 2),
    q('Body Parts', 'easy', 'What connects our head to our body?', 'What connects our head to our body?', ['Shoulder', 'Neck', 'Arm', 'Back'], 2),
    q('Body Parts', 'easy', 'What is at the end of our arm?', 'What is at the end of our arm?', ['Foot', 'Hand', 'Elbow', 'Knee'], 2),
    q('Body Parts', 'easy', 'What is at the end of our leg?', 'What is at the end of our leg?', ['Hand', 'Elbow', 'Foot', 'Knee'], 3),
    q('Body Parts', 'easy', 'Where is our elbow?', 'Where is our elbow?', ['Leg', 'Arm', 'Neck', 'Back'], 2),
    q('Body Parts', 'easy', 'Where is our knee?', 'Where is our knee?', ['Arm', 'Neck', 'Leg', 'Back'], 3),
    q('Body Parts', 'easy', 'What covers our body?', 'What covers our body?', ['Hair', 'Skin', 'Nails', 'Bone'], 2),
    q('Body Parts', 'easy', 'How many ears do humans have?', 'How many ears do humans have?', ['1', '2', '3', '4'], 2),
    q('Body Parts', 'easy', 'What do we use to walk?', 'What do we use to walk?', ['Arms', 'Hands', 'Legs', 'Neck'], 3),
    q('Body Parts', 'easy', 'What do we use to pick things up?', 'What do we use to pick things up?', ['Legs', 'Hands', 'Feet', 'Neck'], 2),
    q('Body Parts', 'easy', 'Which body part pumps blood?', 'Which body part pumps blood?', ['Lungs', 'Brain', 'Heart', 'Stomach'], 3),
    q('Body Parts', 'easy', 'Where is your belly button?', 'Where is your belly button?', ['Back', 'Chest', 'Stomach area', 'Neck'], 3),
    q('Body Parts', 'easy', 'What grows on top of our head?', 'What grows on top of our head?', ['Nails', 'Skin', 'Hair', 'Teeth'], 3),
    q('Body Parts', 'easy', 'What do we use to chew food?', 'What do we use to chew food?', ['Ears', 'Eyes', 'Nose', 'Teeth'], 4),
    q('Body Parts', 'easy', 'How many thumbs do we have?', 'How many thumbs do we have?', ['1', '2', '4', '5'], 2),
    q('Body Parts', 'easy', 'What connects our arm to our body?', 'What connects our arm to our body?', ['Elbow', 'Shoulder', 'Wrist', 'Knee'], 2),
    q('Body Parts', 'easy', 'What connects our leg to our body?', 'What connects our leg to our body?', ['Knee', 'Ankle', 'Hip', 'Wrist'], 3),
    q('Body Parts', 'easy', 'Where is your forehead?', 'Where is your forehead?', ['Below your nose', 'On your arm', 'Above your eyes', 'On your chin'], 3),
    q('Body Parts', 'easy', 'What is your chin?', 'What is your chin?', ['Top of head', 'Bottom of face', 'Side of head', 'Back of head'], 2),
    q('Body Parts', 'easy', 'What do we use to clap?', 'What do we use to clap?', ['Feet', 'Hands', 'Legs', 'Arms'], 2),
    q('Body Parts', 'easy', 'How many lips do humans have?', 'How many lips do humans have?', ['1', '2', '3', '4'], 2),
    q('Body Parts', 'easy', 'What is the longest bone in the body?', 'What is the longest bone in the body?', ['Arm bone', 'Finger bone', 'Leg bone (femur)', 'Neck bone'], 3),

    // ── Family ──
    q('Family', 'easy', 'What do we call our mother\'s mother?', 'What do we call our mother\'s mother?', ['Aunt', 'Sister', 'Grandmother', 'Cousin'], 3),
    q('Family', 'easy', 'What do we call our father\'s father?', 'What do we call our father\'s father?', ['Uncle', 'Brother', 'Grandfather', 'Cousin'], 3),
    q('Family', 'easy', 'What do we call a girl sibling?', 'What do we call a girl sibling?', ['Brother', 'Cousin', 'Uncle', 'Sister'], 4),
    q('Family', 'easy', 'What do we call a boy sibling?', 'What do we call a boy sibling?', ['Sister', 'Brother', 'Niece', 'Cousin'], 2),
    q('Family', 'easy', 'What do we call our father\'s brother?', 'What do we call our father\'s brother?', ['Cousin', 'Uncle', 'Brother', 'Nephew'], 2),
    q('Family', 'easy', 'What do we call our mother\'s sister?', 'What do we call our mother\'s sister?', ['Uncle', 'Niece', 'Aunt', 'Sister'], 3),
    q('Family', 'easy', 'What is a female parent called?', 'What is a female parent called?', ['Father', 'Uncle', 'Mother', 'Aunt'], 3),
    q('Family', 'easy', 'What is a male parent called?', 'What is a male parent called?', ['Mother', 'Aunt', 'Uncle', 'Father'], 4),
    q('Family', 'easy', 'What do we call our uncle\'s children?', 'What do we call our uncle\'s children?', ['Cousins', 'Siblings', 'Nephews', 'Nieces'], 1),
    q('Family', 'easy', 'What is the word for a family with parents and children?', 'What is the word for a family with parents and children?', ['Extended family', 'Nuclear family', 'Single family', 'Large family'], 2),
    q('Family', 'easy', 'What do children call their parents\' parents?', 'What do children call their parents\' parents?', ['Parents', 'Grandparents', 'Aunts and Uncles', 'Cousins'], 2),
    q('Family', 'easy', 'What is the male word for a sibling?', 'What is the male word for a sibling?', ['Sister', 'Niece', 'Brother', 'Aunt'], 3),
    q('Family', 'easy', 'What is a word for your whole family?', 'What is a word for your whole family?', ['Friends', 'Neighbors', 'Relatives', 'Classmates'], 3),
    q('Family', 'easy', 'Who is older, a parent or a grandparent?', 'Who is older, a parent or a grandparent?', ['Parent', 'They\'re the same', 'Grandparent', 'Can\'t tell'], 3),
    q('Family', 'easy', 'What do we call two parents and their children?', 'What do we call two parents and their children?', ['A team', 'A family', 'A group', 'A class'], 2),
    q('Family', 'easy', 'What is a female sibling called?', 'What is a female sibling called?', ['Brother', 'Cousin', 'Aunt', 'Sister'], 4),
    q('Family', 'easy', 'What is a baby in the family called?', 'What is a baby in the family called?', ['Toddler', 'Infant', 'Juvenile', 'Elder'], 2),
    q('Family', 'easy', 'What do we call our parent\'s sister?', 'What do we call our parent\'s sister?', ['Grandmother', 'Cousin', 'Aunt', 'Niece'], 3),
    q('Family', 'easy', 'What do we call our parent\'s brother?', 'What do we call our parent\'s brother?', ['Grandfather', 'Cousin', 'Nephew', 'Uncle'], 4),
    q('Family', 'easy', 'What word describes parents and children living together?', 'What word describes parents and children living together?', ['School', 'Workplace', 'Household', 'Neighborhood'], 3),

    // ── School ──
    q('School', 'easy', 'What do you write with?', 'What do you write with?', ['Ruler', 'Eraser', 'Pencil', 'Scissors'], 3),
    q('School', 'easy', 'What do you use to erase mistakes?', 'What do you use to erase mistakes?', ['Pencil', 'Pen', 'Eraser', 'Ruler'], 3),
    q('School', 'easy', 'What do you use to measure?', 'What do you use to measure?', ['Pencil', 'Ruler', 'Eraser', 'Scissors'], 2),
    q('School', 'easy', 'What do you use to cut paper?', 'What do you use to cut paper?', ['Ruler', 'Glue', 'Scissors', 'Pencil'], 3),
    q('School', 'easy', 'What do you use to stick things?', 'What do you use to stick things?', ['Scissors', 'Glue', 'Ruler', 'Eraser'], 2),
    q('School', 'easy', 'Where do you go to learn?', 'Where do you go to learn?', ['Hospital', 'School', 'Market', 'Bank'], 2),
    q('School', 'easy', 'Who teaches you at school?', 'Who teaches you at school?', ['Doctor', 'Police', 'Teacher', 'Nurse'], 3),
    q('School', 'easy', 'What do you carry books in?', 'What do you carry books in?', ['Bag / Backpack', 'Box', 'Pot', 'Basket'], 1),
    q('School', 'easy', 'What do you write on at school?', 'What do you write on at school?', ['Floor', 'Table', 'Blackboard', 'Window'], 3),
    q('School', 'easy', 'What do you sit on in class?', 'What do you sit on in class?', ['Table', 'Chair', 'Floor', 'Shelf'], 2),
    q('School', 'easy', 'What do you sit at in class?', 'What do you sit at in class?', ['Chair', 'Desk', 'Shelf', 'Board'], 2),
    q('School', 'easy', 'What do you read to learn?', 'What do you read to learn?', ['Newspaper', 'Book', 'Menu', 'Sign'], 2),
    q('School', 'easy', 'What subject uses numbers?', 'What subject uses numbers?', ['Art', 'Music', 'Math', 'PE'], 3),
    q('School', 'easy', 'What subject teaches drawing?', 'What subject teaches drawing?', ['Math', 'Science', 'Art', 'History'], 3),
    q('School', 'easy', 'What subject do you sing in?', 'What subject do you sing in?', ['Math', 'Music', 'PE', 'Science'], 2),
    q('School', 'easy', 'What subject teaches about nature?', 'What subject teaches about nature?', ['Art', 'Math', 'Music', 'Science'], 4),
    q('School', 'easy', 'What do you call the person who runs a school?', 'What do you call the person who runs a school?', ['Teacher', 'Principal', 'Librarian', 'Janitor'], 2),
    q('School', 'easy', 'Where are books kept at school?', 'Where are books kept at school?', ['Gym', 'Lab', 'Library', 'Cafeteria'], 3),
    q('School', 'easy', 'What room do students eat in at school?', 'What room do students eat in at school?', ['Library', 'Gym', 'Lab', 'Cafeteria'], 4),
    q('School', 'easy', 'What do we call a picture of the world?', 'What do we call a picture of the world?', ['Diagram', 'Map', 'Chart', 'Graph'], 2),
    q('School', 'easy', 'How many days are in a school week?', 'How many days are in a school week?', ['3', '4', '5', '6'], 3),
    q('School', 'easy', 'What do you call your school friends?', 'What do you call your school friends?', ['Relatives', 'Classmates', 'Teammates', 'Colleagues'], 2),
    q('School', 'easy', 'What subject teaches reading and writing?', 'What subject teaches reading and writing?', ['Math', 'Music', 'English', 'PE'], 3),
    q('School', 'easy', 'What do you use to color pictures?', 'What do you use to color pictures?', ['Pencil only', 'Crayons or colored pencils', 'Scissors', 'Glue'], 2),
    q('School', 'easy', 'What is a notebook used for?', 'What is a notebook used for?', ['Eating', 'Writing notes', 'Cutting paper', 'Measuring'], 2),
    q('School', 'easy', 'What does a teacher use to write on the board?', 'What does a teacher use to write on the board?', ['Pencil', 'Chalk', 'Crayon', 'Marker only'], 2),
    q('School', 'easy', 'What do you say when you don\'t understand?', 'What do you say when you don\'t understand?', ['Thank you', 'Sorry', 'Can you repeat that?', 'Goodbye'], 3),
    q('School', 'easy', 'What time does school usually start?', 'What time does school usually start?', ['Late morning', 'Afternoon', 'Early morning', 'Evening'], 3),
    q('School', 'easy', 'What do you call students in the same grade?', 'What do you call students in the same grade?', ['Family', 'Classmates', 'Teachers', 'Principals'], 2),
    q('School', 'easy', 'What do you do after finishing an exam?', 'What do you do after finishing an exam?', ['Play immediately', 'Hand in your paper', 'Keep writing', 'Leave the room'], 2),

    // ── Grammar ──
    q('Grammar', 'easy', 'Which word means \'I and others\'?', 'Which word means \'I and others\'?', ['He', 'She', 'We', 'They'], 3),
    q('Grammar', 'easy', 'Which word do we use for a boy?', 'Which word do we use for a boy?', ['She', 'Her', 'He', 'They'], 3),
    q('Grammar', 'easy', 'Which word do we use for a girl?', 'Which word do we use for a girl?', ['He', 'His', 'Him', 'She'], 4),
    q('Grammar', 'easy', 'Which word means more than one person?', 'Which word means more than one person?', ['He', 'She', 'It', 'They'], 4),
    q('Grammar', 'easy', 'What is the plural of \'cat\'?', 'What is the plural of \'cat\'?', ['Cates', 'Cats', 'Caties', 'Cat'], 2),
    q('Grammar', 'easy', 'What is the plural of \'dog\'?', 'What is the plural of \'dog\'?', ['Dogen', 'Doggy', 'Dogs', 'Doges'], 3),
    q('Grammar', 'easy', 'What is the plural of \'child\'?', 'What is the plural of \'child\'?', ['Childs', 'Children', 'Childes', 'Childrens'], 2),
    q('Grammar', 'easy', 'What is the plural of \'man\'?', 'What is the plural of \'man\'?', ['Mans', 'Manes', 'Men', 'Menes'], 3),
    q('Grammar', 'easy', 'What is the plural of \'woman\'?', 'What is the plural of \'woman\'?', ['Womans', 'Women', 'Womes', 'Womens'], 2),
    q('Grammar', 'easy', 'What is the plural of \'foot\'?', 'What is the plural of \'foot\'?', ['Foots', 'Feets', 'Feet', 'Foot'], 3),
    q('Grammar', 'easy', 'What is the plural of \'tooth\'?', 'What is the plural of \'tooth\'?', ['Tooths', 'Teeth', 'Toothes', 'Teethes'], 2),
    q('Grammar', 'easy', 'Which word comes before a vowel sound: \'a\' or \'an\'?', 'Which word comes before a vowel sound: \'a\' or \'an\'?', ['a', 'an', 'the', 'some'], 2),
    q('Grammar', 'easy', 'Which is correct: \'___ apple\'?', 'Which is correct: \'___ apple\'?', ['a apple', 'an apple', 'one apple', 'some apple'], 2),
    q('Grammar', 'easy', 'Which is correct: \'___ book\'?', 'Which is correct: \'___ book\'?', ['an book', 'a book', 'one book', 'two book'], 2),
    q('Grammar', 'easy', 'What is the opposite of \'big\'?', 'What is the opposite of \'big\'?', ['Tall', 'Small', 'Fast', 'Heavy'], 2),
    q('Grammar', 'easy', 'What is the opposite of \'hot\'?', 'What is the opposite of \'hot\'?', ['Warm', 'Cool', 'Cold', 'Mild'], 3),
    q('Grammar', 'easy', 'What is the opposite of \'happy\'?', 'What is the opposite of \'happy\'?', ['Sad', 'Angry', 'Tired', 'Bored'], 1),
    q('Grammar', 'easy', 'What is the opposite of \'tall\'?', 'What is the opposite of \'tall\'?', ['Long', 'Wide', 'Short', 'Fat'], 3),
    q('Grammar', 'easy', 'What is the opposite of \'fast\'?', 'What is the opposite of \'fast\'?', ['Quick', 'Slow', 'Late', 'Heavy'], 2),
    q('Grammar', 'easy', 'What is the opposite of \'open\'?', 'What is the opposite of \'open\'?', ['Lock', 'Close', 'Shut', 'Close / Closed'], 4),
    q('Grammar', 'easy', 'What is the opposite of \'night\'?', 'What is the opposite of \'night\'?', ['Evening', 'Afternoon', 'Day', 'Morning'], 3),
    q('Grammar', 'easy', 'What is the opposite of \'old\' (for people)?', 'What is the opposite of \'old\' (for people)?', ['New', 'Young', 'Fresh', 'Recent'], 2),
    q('Grammar', 'easy', 'What is the opposite of \'clean\'?', 'What is the opposite of \'clean\'?', ['Messy', 'Dirty', 'Ugly', 'Dark'], 2),
    q('Grammar', 'easy', 'What is the opposite of \'hard\'?', 'What is the opposite of \'hard\'?', ['Smooth', 'Light', 'Soft', 'Gentle'], 3),
    q('Grammar', 'easy', 'What is the opposite of \'full\'?', 'What is the opposite of \'full\'?', ['Half', 'Empty', 'Less', 'Hollow'], 2),
    q('Grammar', 'easy', 'Which word is a verb (action word)?', 'Which word is a verb (action word)?', ['Happy', 'Big', 'Run', 'Beautiful'], 3),
    q('Grammar', 'easy', 'Which word is an adjective (describing word)?', 'Which word is an adjective (describing word)?', ['Jump', 'Swim', 'Blue', 'Eat'], 3),
    q('Grammar', 'easy', 'Which word is a noun (name of a thing)?', 'Which word is a noun (name of a thing)?', ['Quickly', 'Beautiful', 'Apple', 'Happy'], 3),
    q('Grammar', 'easy', 'What is the correct sentence?', 'What is the correct sentence?', ['She are happy.', 'She is happy.', 'She am happy.', 'She be happy.'], 2),
    q('Grammar', 'easy', 'What is the correct sentence?', 'What is the correct sentence?', ['They is cats.', 'They am cats.', 'They are cats.', 'They be cats.'], 3),
    q('Grammar', 'easy', 'What is the correct sentence?', 'What is the correct sentence?', ['He have a dog.', 'He has a dog.', 'He had a dog now.', 'He having a dog.'], 2),
    q('Grammar', 'easy', 'Which is a question?', 'Which is a question?', ['I like cats.', 'She runs fast.', 'Do you like cats?', 'They have a dog.'], 3),
    q('Grammar', 'easy', 'Which sentence ends with a period?', 'Which sentence ends with a period?', ['What is this', 'Do you like cats', 'I like cats.', 'Come here'], 3),
    q('Grammar', 'easy', 'Which sentence ends with a question mark?', 'Which sentence ends with a question mark?', ['I like cats.', 'What is this?', 'Run fast!', 'She is tall.'], 2),
    q('Grammar', 'easy', 'Which word shows action: \'The dog ___ fast.\'?', 'Which word shows action: \'The dog ___ fast.\'?', ['big', 'runs', 'happy', 'tall'], 2),
    q('Grammar', 'easy', 'Which word is a color?', 'Which word is a color?', ['Jump', 'Run', 'Blue', 'Fast'], 3),
    q('Grammar', 'easy', 'What is the correct: \'I ___ a student.\'?', 'What is the correct: \'I ___ a student.\'?', ['is', 'are', 'am', 'be'], 3),
    q('Grammar', 'easy', 'What is the correct: \'You ___ my friend.\'?', 'What is the correct: \'You ___ my friend.\'?', ['is', 'are', 'am', 'be'], 2),
    q('Grammar', 'easy', 'What is the correct: \'He ___ tall.\'?', 'What is the correct: \'He ___ tall.\'?', ['are', 'am', 'is', 'be'], 3),
    q('Grammar', 'easy', 'What is the correct: \'We ___ happy.\'?', 'What is the correct: \'We ___ happy.\'?', ['is', 'am', 'be', 'are'], 4),
    q('Grammar', 'easy', 'What is the past tense of \'run\'?', 'What is the past tense of \'run\'?', ['Runned', 'Running', 'Ran', 'Runs'], 3),
    q('Grammar', 'easy', 'What is the past tense of \'eat\'?', 'What is the past tense of \'eat\'?', ['Eated', 'Eating', 'Eats', 'Ate'], 4),
    q('Grammar', 'easy', 'What is the past tense of \'go\'?', 'What is the past tense of \'go\'?', ['Goed', 'Going', 'Goes', 'Went'], 4),
    q('Grammar', 'easy', 'What is the past tense of \'see\'?', 'What is the past tense of \'see\'?', ['Seed', 'Seeing', 'Saw', 'Sees'], 3),
    q('Grammar', 'easy', 'What is the past tense of \'have\'?', 'What is the past tense of \'have\'?', ['Haved', 'Having', 'Has', 'Had'], 4),
    q('Grammar', 'easy', 'What does \'big\' mean?', 'What does \'big\' mean?', ['Small', 'Large', 'Short', 'Fast'], 2),
    q('Grammar', 'easy', 'What does \'happy\' mean?', 'What does \'happy\' mean?', ['Sad', 'Angry', 'Joyful', 'Tired'], 3),
    q('Grammar', 'easy', 'What does \'fast\' mean?', 'What does \'fast\' mean?', ['Slow', 'Quick', 'Quiet', 'Tall'], 2),
    q('Grammar', 'easy', 'Which sentence is correct?', 'Which sentence is correct?', ['She don\'t like cats.', 'She doesn\'t likes cats.', 'She doesn\'t like cats.', 'She not like cats.'], 3),
    q('Grammar', 'easy', 'Which is the correct question?', 'Which is the correct question?', ['Do she have a cat?', 'Does she has a cat?', 'Does she have a cat?', 'Have she a cat?'], 3),
    q('Grammar', 'easy', 'What does \'beautiful\' describe?', 'What does \'beautiful\' describe?', ['An action', 'Something lovely to look at', 'A place', 'A sound'], 2),
    q('Grammar', 'easy', 'What type of word is \'quickly\'?', 'What type of word is \'quickly\'?', ['Noun', 'Verb', 'Adverb', 'Adjective'], 3),
    q('Grammar', 'easy', 'What type of word is \'dog\'?', 'What type of word is \'dog\'?', ['Verb', 'Adjective', 'Adverb', 'Noun'], 4),
    q('Grammar', 'easy', 'Which word is a number?', 'Which word is a number?', ['Red', 'Three', 'Run', 'Big'], 2),
    q('Grammar', 'easy', 'Which is correct?', 'Which is correct?', ['There are a apple.', 'There is an apple.', 'There is a apple.', 'There are an apple.'], 2),
    q('Grammar', 'easy', 'What is the correct plural: \'one box, two ___\'?', 'What is the correct plural: \'one box, two ___\'?', ['Boxs', 'Boxes', 'Boxies', 'Boces'], 2),
    q('Grammar', 'easy', 'What is the correct plural: \'one bus, two ___\'?', 'What is the correct plural: \'one bus, two ___\'?', ['Buss', 'Busies', 'Buses', 'Bus'], 3),
    q('Grammar', 'easy', 'What is the correct plural: \'one city, two ___\'?', 'What is the correct plural: \'one city, two ___\'?', ['Citys', 'Cities', 'Cityes', 'Citiss'], 2),
    q('Grammar', 'easy', 'What punctuation ends a sentence?', 'What punctuation ends a sentence?', ['Comma', 'Apostrophe', 'Period', 'Colon'], 3),
    q('Grammar', 'easy', 'What punctuation is used in a question?', 'What punctuation is used in a question?', ['Period', 'Comma', 'Exclamation mark', 'Question mark'], 4),

    // ── Numbers & Math ──
    q('Numbers & Math', 'easy', 'How much is 2 + 3?', 'How much is 2 + 3?', ['4', '5', '6', '7'], 2),
    q('Numbers & Math', 'easy', 'How much is 5 + 5?', 'How much is 5 + 5?', ['8', '9', '10', '11'], 3),
    q('Numbers & Math', 'easy', 'How much is 7 + 3?', 'How much is 7 + 3?', ['9', '10', '11', '12'], 2),
    q('Numbers & Math', 'easy', 'How much is 4 + 6?', 'How much is 4 + 6?', ['8', '9', '11', '10'], 4),
    q('Numbers & Math', 'easy', 'How much is 8 + 2?', 'How much is 8 + 2?', ['9', '10', '11', '12'], 2),
    q('Numbers & Math', 'easy', 'How much is 10 - 3?', 'How much is 10 - 3?', ['6', '7', '8', '9'], 2),
    q('Numbers & Math', 'easy', 'How much is 9 - 4?', 'How much is 9 - 4?', ['4', '5', '6', '7'], 2),
    q('Numbers & Math', 'easy', 'How much is 8 - 5?', 'How much is 8 - 5?', ['2', '3', '4', '5'], 2),
    q('Numbers & Math', 'easy', 'How much is 10 - 7?', 'How much is 10 - 7?', ['2', '3', '4', '5'], 2),
    q('Numbers & Math', 'easy', 'How much is 6 - 2?', 'How much is 6 - 2?', ['3', '4', '5', '6'], 2),
    q('Numbers & Math', 'easy', 'How do you write twelve in numbers?', 'How do you write twelve in numbers?', ['11', '12', '13', '21'], 2),
    q('Numbers & Math', 'easy', 'How do you write fifteen in numbers?', 'How do you write fifteen in numbers?', ['13', '14', '15', '50'], 3),
    q('Numbers & Math', 'easy', 'How do you write twenty in numbers?', 'How do you write twenty in numbers?', ['12', '21', '20', '22'], 3),
    q('Numbers & Math', 'easy', 'What number comes after 19?', 'What number comes after 19?', ['18', '21', '20', '22'], 3),
    q('Numbers & Math', 'easy', 'What number comes before 10?', 'What number comes before 10?', ['8', '9', '11', '12'], 2),
    q('Numbers & Math', 'easy', 'What is half of 10?', 'What is half of 10?', ['4', '5', '6', '8'], 2),
    q('Numbers & Math', 'easy', 'What is double of 5?', 'What is double of 5?', ['8', '9', '10', '12'], 3),
    q('Numbers & Math', 'easy', 'Which number is the biggest?', 'Which number is the biggest?', ['15', '20', '18', '12'], 2),
    q('Numbers & Math', 'easy', 'Which number is the smallest?', 'Which number is the smallest?', ['20', '15', '8', '12'], 3),
    q('Numbers & Math', 'easy', 'How many days are in a week?', 'How many days are in a week?', ['5', '6', '7', '8'], 3),
    q('Numbers & Math', 'easy', 'How many months are in a year?', 'How many months are in a year?', ['10', '11', '12', '13'], 3),
    q('Numbers & Math', 'easy', 'How many hours are in a day?', 'How many hours are in a day?', ['12', '20', '24', '30'], 3),
    q('Numbers & Math', 'easy', 'How many minutes are in an hour?', 'How many minutes are in an hour?', ['30', '60', '90', '100'], 2),
    q('Numbers & Math', 'easy', 'How many seconds are in a minute?', 'How many seconds are in a minute?', ['30', '60', '90', '100'], 2),
    q('Numbers & Math', 'easy', 'What number is between 5 and 7?', 'What number is between 5 and 7?', ['4', '6', '8', '9'], 2),
    q('Numbers & Math', 'easy', 'What is 3 × 2?', 'What is 3 × 2?', ['4', '5', '6', '7'], 3),
    q('Numbers & Math', 'easy', 'What is 2 × 4?', 'What is 2 × 4?', ['6', '7', '8', '9'], 3),
    q('Numbers & Math', 'easy', 'What is 5 × 2?', 'What is 5 × 2?', ['8', '9', '10', '12'], 3),
    q('Numbers & Math', 'easy', 'What is 10 ÷ 2?', 'What is 10 ÷ 2?', ['3', '4', '5', '6'], 3),
    q('Numbers & Math', 'easy', 'What is 6 ÷ 2?', 'What is 6 ÷ 2?', ['2', '3', '4', '5'], 2),
    q('Numbers & Math', 'easy', 'What is the number before 100?', 'What is the number before 100?', ['98', '99', '101', '90'], 2),
    q('Numbers & Math', 'easy', 'What is 1 + 1 + 1?', 'What is 1 + 1 + 1?', ['2', '3', '4', '5'], 2),
    q('Numbers & Math', 'easy', 'What does \'dozen\' mean?', 'What does \'dozen\' mean?', ['10', '11', '12', '13'], 3),
    q('Numbers & Math', 'easy', 'Which number is even?', 'Which number is even?', ['3', '5', '7', '8'], 4),
    q('Numbers & Math', 'easy', 'Which number is odd?', 'Which number is odd?', ['2', '4', '7', '8'], 3),
    q('Numbers & Math', 'easy', 'What comes after one hundred?', 'What comes after one hundred?', ['Ninety-nine', 'One hundred one', 'Two hundred', 'One thousand'], 2),
    q('Numbers & Math', 'easy', 'What is 15 + 5?', 'What is 15 + 5?', ['18', '19', '20', '21'], 3),
    q('Numbers & Math', 'easy', 'What is 20 - 10?', 'What is 20 - 10?', ['5', '8', '10', '12'], 3),
    q('Numbers & Math', 'easy', 'Which is correct: 5 ___ 3 = 8?', 'Which is correct: 5 ___ 3 = 8?', ['-', '×', '+', '÷'], 3),
    q('Numbers & Math', 'easy', 'Which is correct: 10 ___ 2 = 5?', 'Which is correct: 10 ___ 2 = 5?', ['+', '-', '×', '÷'], 4),

    // ── Weather & Seasons ──
    q('Weather & Seasons', 'easy', 'How many seasons are there?', 'How many seasons are there?', ['2', '3', '4', '5'], 3),
    q('Weather & Seasons', 'easy', 'Which season is the hottest?', 'Which season is the hottest?', ['Spring', 'Summer', 'Autumn', 'Winter'], 2),
    q('Weather & Seasons', 'easy', 'Which season is the coldest?', 'Which season is the coldest?', ['Spring', 'Summer', 'Autumn', 'Winter'], 4),
    q('Weather & Seasons', 'easy', 'When do leaves fall from trees?', 'When do leaves fall from trees?', ['Spring', 'Summer', 'Autumn', 'Winter'], 3),
    q('Weather & Seasons', 'easy', 'When do flowers bloom?', 'When do flowers bloom?', ['Winter', 'Autumn', 'Spring', 'Summer'], 3),
    q('Weather & Seasons', 'easy', 'What falls from the sky in winter?', 'What falls from the sky in winter?', ['Rain', 'Snow', 'Hail', 'All of these'], 4),
    q('Weather & Seasons', 'easy', 'What do we use when it rains?', 'What do we use when it rains?', ['Fan', 'Sunglasses', 'Umbrella', 'Scarf'], 3),
    q('Weather & Seasons', 'easy', 'What does the sun give us?', 'What does the sun give us?', ['Rain', 'Snow', 'Heat and light', 'Wind'], 3),
    q('Weather & Seasons', 'easy', 'What is it called when water falls from clouds?', 'What is it called when water falls from clouds?', ['Wind', 'Snow', 'Rain', 'Fog'], 3),
    q('Weather & Seasons', 'easy', 'Which weather is sunny?', 'Which weather is sunny?', ['Rainy', 'Cloudy', 'Foggy', 'Clear and bright'], 4),
    q('Weather & Seasons', 'easy', 'What do we wear in winter?', 'What do we wear in winter?', ['T-shirt', 'Coat and scarf', 'Swimsuit', 'Shorts'], 2),
    q('Weather & Seasons', 'easy', 'What do we wear in summer?', 'What do we wear in summer?', ['Heavy coat', 'Boots', 'T-shirt and shorts', 'Thick sweater'], 3),
    q('Weather & Seasons', 'easy', 'What is a weather condition with no sun?', 'What is a weather condition with no sun?', ['Sunny', 'Cloudy', 'Hot', 'Bright'], 2),
    q('Weather & Seasons', 'easy', 'When is it safe to go to the beach?', 'When is it safe to go to the beach?', ['Winter', 'Rainy season', 'Summer', 'Stormy weather'], 3),
    q('Weather & Seasons', 'easy', 'What comes after lightning?', 'What comes after lightning?', ['Rain', 'Thunder', 'Snow', 'Wind'], 2),
    q('Weather & Seasons', 'easy', 'What is fog?', 'What is fog?', ['Low cloud near ground', 'Heavy rain', 'Strong wind', 'Hot weather'], 1),
    q('Weather & Seasons', 'easy', 'What instrument measures temperature?', 'What instrument measures temperature?', ['Ruler', 'Thermometer', 'Scale', 'Clock'], 2),
    q('Weather & Seasons', 'easy', 'What is a tornado?', 'What is a tornado?', ['A type of rain', 'A spinning windstorm', 'A type of snow', 'A calm day'], 2),
    q('Weather & Seasons', 'easy', 'What month does summer usually start in (Northern Hemisphere)?', 'What month does summer usually start in (Northern Hemisphere)?', ['March', 'April', 'June', 'September'], 3),
    q('Weather & Seasons', 'easy', 'What is \'windy\' weather?', 'What is \'windy\' weather?', ['Hot and sunny', 'Cold and snowy', 'With strong wind', 'Foggy and cloudy'], 3),
    q('Weather & Seasons', 'easy', 'What does \'temperature\' measure?', 'What does \'temperature\' measure?', ['Wind speed', 'Rainfall amount', 'How hot or cold something is', 'Cloud amount'], 3),
    q('Weather & Seasons', 'easy', 'What is a weather forecast?', 'What is a weather forecast?', ['A type of weather', 'A prediction of future weather', 'A weather instrument', 'A season'], 2),
    q('Weather & Seasons', 'easy', 'What is a rainbow caused by?', 'What is a rainbow caused by?', ['Snow', 'Wind', 'Fog', 'Sun and rain together'], 4),
    q('Weather & Seasons', 'easy', 'How many colors are in a rainbow?', 'How many colors are in a rainbow?', ['5', '6', '7', '8'], 3),
    q('Weather & Seasons', 'easy', 'What season comes after summer?', 'What season comes after summer?', ['Spring', 'Winter', 'Autumn', 'nan'], 3),

    // ── Daily Activities ──
    q('Daily Activities', 'easy', 'What do you do first in the morning?', 'What do you do first in the morning?', ['Have lunch', 'Go to sleep', 'Wake up', 'Do homework'], 3),
    q('Daily Activities', 'easy', 'What do you do before going to bed?', 'What do you do before going to bed?', ['Have breakfast', 'Brush your teeth', 'Play outside', 'Go to school'], 2),
    q('Daily Activities', 'easy', 'What do you do three times a day for your teeth?', 'What do you do three times a day for your teeth?', ['Comb hair', 'Brush teeth', 'Wash hands', 'Exercise'], 2),
    q('Daily Activities', 'easy', 'When do you eat breakfast?', 'When do you eat breakfast?', ['At night', 'In the afternoon', 'In the morning', 'After dinner'], 3),
    q('Daily Activities', 'easy', 'When do you eat dinner?', 'When do you eat dinner?', ['Morning', 'Afternoon', 'Evening', 'Midnight'], 3),
    q('Daily Activities', 'easy', 'What do you do when you feel sleepy?', 'What do you do when you feel sleepy?', ['Eat', 'Exercise', 'Sleep', 'Study'], 3),
    q('Daily Activities', 'easy', 'What do you say when you greet someone in the morning?', 'What do you say when you greet someone in the morning?', ['Good night', 'Good afternoon', 'Good evening', 'Good morning'], 4),
    q('Daily Activities', 'easy', 'What do you say when you meet someone?', 'What do you say when you meet someone?', ['Goodbye', 'Hello', 'Thank you', 'Sorry'], 2),
    q('Daily Activities', 'easy', 'What do you say when you leave?', 'What do you say when you leave?', ['Hello', 'How are you?', 'Goodbye', 'Please'], 3),
    q('Daily Activities', 'easy', 'What do you say to show gratitude?', 'What do you say to show gratitude?', ['Sorry', 'Please', 'Thank you', 'Hello'], 3),
    q('Daily Activities', 'easy', 'What do you say when you make a mistake?', 'What do you say when you make a mistake?', ['Thank you', 'Please', 'Sorry', 'Hello'], 3),
    q('Daily Activities', 'easy', 'When is midnight?', 'When is midnight?', ['12 noon', '12 at night', '6 in evening', 'Early morning'], 2),
    q('Daily Activities', 'easy', 'What comes after Tuesday?', 'What comes after Tuesday?', ['Monday', 'Wednesday', 'Thursday', 'Friday'], 2),
    q('Daily Activities', 'easy', 'What comes after Wednesday?', 'What comes after Wednesday?', ['Tuesday', 'Thursday', 'Friday', 'Monday'], 2),
    q('Daily Activities', 'easy', 'What is the first day of the week (Sunday calendar)?', 'What is the first day of the week (Sunday calendar)?', ['Monday', 'Friday', 'Sunday', 'Saturday'], 3),
    q('Daily Activities', 'easy', 'What is the last day of the school week?', 'What is the last day of the school week?', ['Thursday', 'Sunday', 'Saturday', 'Friday'], 4),
    q('Daily Activities', 'easy', 'What are Saturday and Sunday called?', 'What are Saturday and Sunday called?', ['Weekdays', 'School days', 'Weekend', 'Workdays'], 3),
    q('Daily Activities', 'easy', 'How many days are in a week?', 'How many days are in a week?', ['5', '6', '7', '8'], 3),
    q('Daily Activities', 'easy', 'What do you do in PE class?', 'What do you do in PE class?', ['Read books', 'Exercise and play sports', 'Draw pictures', 'Sing songs'], 2),
    q('Daily Activities', 'easy', 'What time do most schools start?', 'What time do most schools start?', ['5am', '7-8am', '10am', '12pm'], 2),
    q('Daily Activities', 'easy', 'What does a calendar show?', 'What does a calendar show?', ['Weather', 'Time of day', 'Days, months, and years', 'Temperature'], 3),
    q('Daily Activities', 'easy', 'What is your schedule?', 'What is your schedule?', ['A type of sport', 'A plan showing times and activities', 'A type of food', 'A weather report'], 2),
    q('Daily Activities', 'easy', 'How many months have 31 days?', 'How many months have 31 days?', ['3', '5', '7', '9'], 3),
    q('Daily Activities', 'easy', 'Which month is the last of the year?', 'Which month is the last of the year?', ['November', 'October', 'December', 'January'], 3),
    q('Daily Activities', 'easy', 'Which month is the first of the year?', 'Which month is the first of the year?', ['February', 'January', 'March', 'December'], 2),
    q('Daily Activities', 'easy', 'What is the day after today called?', 'What is the day after today called?', ['Yesterday', 'Today', 'Tomorrow', 'Later'], 3),
    q('Daily Activities', 'easy', 'What is the day before today called?', 'What is the day before today called?', ['Tomorrow', 'Yesterday', 'Later', 'Soon'], 2),
    q('Daily Activities', 'easy', 'What do you do on a school holiday?', 'What do you do on a school holiday?', ['Go to class', 'Study all day', 'Rest and play', 'Take exams'], 3),
    q('Daily Activities', 'easy', 'What is an alarm clock used for?', 'What is an alarm clock used for?', ['Telling stories', 'Cooking food', 'Waking you up', 'Measuring temperature'], 3),
    q('Daily Activities', 'easy', 'What do you put on after a shower?', 'What do you put on after a shower?', ['Pajamas', 'Clothes', 'Swimsuit', 'Nothing'], 2),

    // ── Places & Transport ──
    q('Places & Transport', 'easy', 'Where do sick people go?', 'Where do sick people go?', ['School', 'Hospital', 'Market', 'Library'], 2),
    q('Places & Transport', 'easy', 'Where do you buy things?', 'Where do you buy things?', ['Hospital', 'School', 'Market / Shop', 'Library'], 3),
    q('Places & Transport', 'easy', 'Where do you borrow books?', 'Where do you borrow books?', ['Market', 'Hospital', 'Library', 'School only'], 3),
    q('Places & Transport', 'easy', 'Where do planes land and take off?', 'Where do planes land and take off?', ['Station', 'Port', 'Airport', 'Bus stop'], 3),
    q('Places & Transport', 'easy', 'Where do trains stop?', 'Where do trains stop?', ['Airport', 'Station', 'Port', 'Bus stop'], 2),
    q('Places & Transport', 'easy', 'Where do ships dock?', 'Where do ships dock?', ['Airport', 'Station', 'Port / Harbor', 'Bus stop'], 3),
    q('Places & Transport', 'easy', 'What vehicle has two wheels?', 'What vehicle has two wheels?', ['Car', 'Truck', 'Bicycle', 'Bus'], 3),
    q('Places & Transport', 'easy', 'What vehicle has four wheels and many seats?', 'What vehicle has four wheels and many seats?', ['Bicycle', 'Motorbike', 'Car', 'Bus'], 4),
    q('Places & Transport', 'easy', 'What vehicle travels in water?', 'What vehicle travels in water?', ['Airplane', 'Car', 'Train', 'Ship'], 4),
    q('Places & Transport', 'easy', 'What vehicle travels in the sky?', 'What vehicle travels in the sky?', ['Car', 'Bicycle', 'Airplane', 'Boat'], 3),
    q('Places & Transport', 'easy', 'What vehicle travels on rails?', 'What vehicle travels on rails?', ['Car', 'Train', 'Bicycle', 'Truck'], 2),
    q('Places & Transport', 'easy', 'What do we call a person who drives a car?', 'What do we call a person who drives a car?', ['Pilot', 'Captain', 'Driver', 'Conductor'], 3),
    q('Places & Transport', 'easy', 'What do we call a person who flies a plane?', 'What do we call a person who flies a plane?', ['Driver', 'Sailor', 'Pilot', 'Captain'], 3),
    q('Places & Transport', 'easy', 'Where do you go to pray?', 'Where do you go to pray?', ['Hospital', 'Market', 'Temple / Church', 'Library'], 3),
    q('Places & Transport', 'easy', 'Where do firefighters work?', 'Where do firefighters work?', ['Hospital', 'Fire station', 'Police station', 'Market'], 2),
    q('Places & Transport', 'easy', 'Where do police officers work?', 'Where do police officers work?', ['Hospital', 'Fire station', 'Police station', 'Market'], 3),
    q('Places & Transport', 'easy', 'What do you call the place where you live?', 'What do you call the place where you live?', ['Office', 'School', 'Home', 'Hospital'], 3),
    q('Places & Transport', 'easy', 'What is a road with many lanes called?', 'What is a road with many lanes called?', ['Street', 'Path', 'Highway', 'Alley'], 3),
    q('Places & Transport', 'easy', 'What signal tells drivers to stop?', 'What signal tells drivers to stop?', ['Green light', 'Yellow light', 'Red light', 'White light'], 3),
    q('Places & Transport', 'easy', 'What signal tells drivers to go?', 'What signal tells drivers to go?', ['Red light', 'Yellow light', 'Green light', 'Blue light'], 3),
    q('Places & Transport', 'easy', 'What do you call a place where children play?', 'What do you call a place where children play?', ['Library', 'Playground', 'Hospital', 'Office'], 2),
    q('Places & Transport', 'easy', 'What is a zoo?', 'What is a zoo?', ['A place to buy things', 'A school for animals', 'A place where animals are kept', 'A hospital'], 3),
    q('Places & Transport', 'easy', 'Where do farmers work?', 'Where do farmers work?', ['Office', 'Factory', 'Farm', 'Hospital'], 3),
    q('Places & Transport', 'easy', 'What is a skyscraper?', 'What is a skyscraper?', ['A type of vehicle', 'A very tall building', 'A type of road', 'A small house'], 2),
    q('Places & Transport', 'easy', 'Where do students learn?', 'Where do students learn?', ['Hospital', 'Market', 'School', 'Factory'], 3),
    q('Places & Transport', 'easy', 'What vehicle do most children take to school?', 'What vehicle do most children take to school?', ['Airplane', 'Ship', 'School bus', 'Helicopter'], 3),
    q('Places & Transport', 'easy', 'What is a pedestrian?', 'What is a pedestrian?', ['A person who drives', 'A person who walks', 'A person who flies', 'A type of road'], 2),
    q('Places & Transport', 'easy', 'What is a crosswalk?', 'What is a crosswalk?', ['A car park', 'A marked area for crossing the road', 'A type of road', 'A bridge'], 2),
    q('Places & Transport', 'easy', 'Where do people swim laps?', 'Where do people swim laps?', ['Pond', 'Lake', 'Ocean', 'Swimming pool'], 4),
    q('Places & Transport', 'easy', 'What do we call a person\'s permanent address?', 'What do we call a person\'s permanent address?', ['Workplace', 'School', 'Home address', 'Hotel'], 3),

    // ── Reading Comprehension ──
    q('Reading Comprehension', 'easy', '\'The cat is on the mat.\' Where is the cat?', '\'The cat is on the mat.\' Where is the cat?', ['Under the mat', 'Beside the mat', 'On the mat', 'Behind the mat'], 3),
    q('Reading Comprehension', 'easy', '\'Tom has a red ball.\' What color is the ball?', '\'Tom has a red ball.\' What color is the ball?', ['Blue', 'Green', 'Yellow', 'Red'], 4),
    q('Reading Comprehension', 'easy', '\'Sara eats an apple every day.\' What does Sara eat?', '\'Sara eats an apple every day.\' What does Sara eat?', ['A banana', 'An orange', 'An apple', 'A mango'], 3),
    q('Reading Comprehension', 'easy', '\'It is raining outside.\' What is the weather?', '\'It is raining outside.\' What is the weather?', ['Sunny', 'Cloudy', 'Rainy', 'Snowy'], 3),
    q('Reading Comprehension', 'easy', '\'Ben is 7 years old.\' How old is Ben?', '\'Ben is 7 years old.\' How old is Ben?', ['6', '7', '8', '9'], 2),
    q('Reading Comprehension', 'easy', '\'The dog is big and brown.\' What color is the dog?', '\'The dog is big and brown.\' What color is the dog?', ['Black', 'White', 'Brown', 'Grey'], 3),
    q('Reading Comprehension', 'easy', '\'My mother is a doctor.\' What is mother\'s job?', '\'My mother is a doctor.\' What is mother\'s job?', ['Teacher', 'Nurse', 'Doctor', 'Chef'], 3),
    q('Reading Comprehension', 'easy', '\'We go to school by bus.\' How do they go to school?', '\'We go to school by bus.\' How do they go to school?', ['By car', 'By bike', 'By bus', 'On foot'], 3),
    q('Reading Comprehension', 'easy', '\'The flower is pink and yellow.\' How many colors are mentioned?', '\'The flower is pink and yellow.\' How many colors are mentioned?', ['1', '2', '3', '4'], 2),
    q('Reading Comprehension', 'easy', '\'Lily has two cats and one dog.\' How many pets does Lily have?', '\'Lily has two cats and one dog.\' How many pets does Lily have?', ['2', '3', '4', '5'], 2),
    q('Reading Comprehension', 'easy', '\'Peter wakes up at 7 o\'clock.\' When does Peter wake up?', '\'Peter wakes up at 7 o\'clock.\' When does Peter wake up?', ['6 o\'clock', '7 o\'clock', '8 o\'clock', '9 o\'clock'], 2),
    q('Reading Comprehension', 'easy', '\'The bird sings in the tree.\' Where does the bird sing?', '\'The bird sings in the tree.\' Where does the bird sing?', ['In the cage', 'On the ground', 'In the tree', 'In the house'], 3),
    q('Reading Comprehension', 'easy', '\'My dad is tall and strong.\' What describes dad?', '\'My dad is tall and strong.\' What describes dad?', ['Short and weak', 'Tall and strong', 'Tall and thin', 'Short and strong'], 2),
    q('Reading Comprehension', 'easy', '\'Sam drinks milk every morning.\' What does Sam drink?', '\'Sam drinks milk every morning.\' What does Sam drink?', ['Juice', 'Water', 'Milk', 'Tea'], 3),
    q('Reading Comprehension', 'easy', '\'There are five fish in the tank.\' How many fish are there?', '\'There are five fish in the tank.\' How many fish are there?', ['3', '4', '5', '6'], 3),
    q('Reading Comprehension', 'easy', '\'Anna wears a blue dress today.\' What color is Anna\'s dress?', '\'Anna wears a blue dress today.\' What color is Anna\'s dress?', ['Red', 'Blue', 'Green', 'Yellow'], 2),
    q('Reading Comprehension', 'easy', '\'The baby is sleeping in the crib.\' What is the baby doing?', '\'The baby is sleeping in the crib.\' What is the baby doing?', ['Playing', 'Eating', 'Sleeping', 'Crying'], 3),
    q('Reading Comprehension', 'easy', '\'Jake and his friends play football.\' What sport do they play?', '\'Jake and his friends play football.\' What sport do they play?', ['Basketball', 'Tennis', 'Football', 'Volleyball'], 3),
    q('Reading Comprehension', 'easy', '\'Mom bakes a chocolate cake.\' What does mom bake?', '\'Mom bakes a chocolate cake.\' What does mom bake?', ['A bread', 'A pie', 'A cookie', 'A chocolate cake'], 4),
    q('Reading Comprehension', 'easy', '\'The sun sets in the west.\' Where does the sun set?', '\'The sun sets in the west.\' Where does the sun set?', ['East', 'North', 'South', 'West'], 4),
    q('Reading Comprehension', 'easy', '\'She is very CHEERFUL today.\' What does cheerful mean?', '\'She is very CHEERFUL today.\' What does cheerful mean?', ['Sad', 'Angry', 'Happy', 'Tired'], 3),
    q('Reading Comprehension', 'easy', '\'The baby CRIED all night.\' What did the baby do?', '\'The baby CRIED all night.\' What did the baby do?', ['Laughed', 'Slept', 'Cried', 'Played'], 3),
    q('Reading Comprehension', 'easy', '\'He RUNS to school every day.\' What does he do?', '\'He RUNS to school every day.\' What does he do?', ['Walk', 'Run', 'Ride', 'Skip'], 2),
    q('Reading Comprehension', 'easy', '\'The ENORMOUS elephant sat down.\' What does enormous mean?', '\'The ENORMOUS elephant sat down.\' What does enormous mean?', ['Very small', 'Very fast', 'Very heavy', 'Very big'], 4),
    q('Reading Comprehension', 'easy', '\'She WHISPERED a secret.\' What does whispered mean?', '\'She WHISPERED a secret.\' What does whispered mean?', ['Spoke very loudly', 'Spoke very softly', 'Shouted', 'Sang'], 2),
    q('Reading Comprehension', 'easy', '\'The cake was DELICIOUS.\' What does delicious mean?', '\'The cake was DELICIOUS.\' What does delicious mean?', ['Very ugly', 'Very hot', 'Very tasty', 'Very cold'], 3),
    q('Reading Comprehension', 'easy', '\'He was FURIOUS when he lost.\' What does furious mean?', '\'He was FURIOUS when he lost.\' What does furious mean?', ['Very happy', 'Very sad', 'Very tired', 'Very angry'], 4),
    q('Reading Comprehension', 'easy', '\'The room was FILTHY.\' What does filthy mean?', '\'The room was FILTHY.\' What does filthy mean?', ['Very clean', 'Very bright', 'Very dirty', 'Very big'], 3),
    q('Reading Comprehension', 'easy', '\'She was EXHAUSTED after the race.\' What does exhausted mean?', '\'She was EXHAUSTED after the race.\' What does exhausted mean?', ['Very excited', 'Very tired', 'Very happy', 'Very hungry'], 2),
    q('Reading Comprehension', 'easy', '\'The boy was BRAVE.\' What does brave mean?', '\'The boy was BRAVE.\' What does brave mean?', ['Scared', 'Funny', 'Courageous', 'Clever'], 3),
    q('Reading Comprehension', 'easy', 'Which is NOT a complete sentence?', 'Which is NOT a complete sentence?', ['I like cats.', 'She runs fast.', 'The big dog.', 'We eat lunch.'], 3),
    q('Reading Comprehension', 'easy', 'Which sentence starts correctly?', 'Which sentence starts correctly?', ['the dog runs.', 'The dog runs.', 'the Dog runs.', 'the dog Runs.'], 2),
    q('Reading Comprehension', 'easy', 'Which sentence has correct punctuation?', 'Which sentence has correct punctuation?', ['I am happy', 'I am happy?', 'I am happy.', 'i am happy.'], 3),
    q('Reading Comprehension', 'easy', 'Which question is correct?', 'Which question is correct?', ['where is my book?', 'Where is my book?', 'where Is my Book?', 'Where Is My Book?'], 2),
    q('Reading Comprehension', 'easy', 'Which word fits: \'She ___ to school.\'?', 'Which word fits: \'She ___ to school.\'?', ['walk', 'walks', 'walking', 'walked'], 2),
    q('Reading Comprehension', 'easy', 'Which word fits: \'They ___ lunch.\'?', 'Which word fits: \'They ___ lunch.\'?', ['eat', 'eats', 'ate', 'eaten'], 1),
    q('Reading Comprehension', 'easy', 'Which word fits: \'I ___ a book.\'?', 'Which word fits: \'I ___ a book.\'?', ['reads', 'read', 'reading', 'readed'], 2),
    q('Reading Comprehension', 'easy', 'Which word fits: \'He ___ football.\'?', 'Which word fits: \'He ___ football.\'?', ['play', 'plays', 'played', 'playing'], 2),
    q('Reading Comprehension', 'easy', 'Which word fits: \'The cat ___ on the table.\'?', 'Which word fits: \'The cat ___ on the table.\'?', ['sit', 'sits', 'sitting', 'sat'], 2),
    q('Reading Comprehension', 'easy', 'Which word fits: \'We ___ in the park.\'?', 'Which word fits: \'We ___ in the park.\'?', ['plays', 'play', 'playing', 'played'], 2),
    q('Reading Comprehension', 'easy', '\'Mary has a little lamb. Its fleece is white as snow.\' What color is the lamb\'s fleece?', '\'Mary has a little lamb. Its fleece is white as snow.\' What color is the lamb\'s fleece?', ['Black', 'Brown', 'White', 'Grey'], 3),
    q('Reading Comprehension', 'easy', '\'Jack and Jill went up the hill to fetch a pail of water.\' What did they go to fetch?', '\'Jack and Jill went up the hill to fetch a pail of water.\' What did they go to fetch?', ['A bucket of milk', 'A pail of juice', 'A pail of water', 'A basket of food'], 3),
    q('Reading Comprehension', 'easy', '\'Humpty Dumpty sat on a wall.\' What did Humpty Dumpty sit on?', '\'Humpty Dumpty sat on a wall.\' What did Humpty Dumpty sit on?', ['A chair', 'A fence', 'A wall', 'A rock'], 3),
    q('Reading Comprehension', 'easy', '\'Old MacDonald had a farm. On his farm he had a cow.\' What animal did Old MacDonald have?', '\'Old MacDonald had a farm. On his farm he had a cow.\' What animal did Old MacDonald have?', ['A sheep', 'A pig', 'A horse', 'A cow'], 4),
    q('Reading Comprehension', 'easy', '\'Little Miss Muffet sat on a tuffet, eating her curds and whey.\' What was Miss Muffet doing?', '\'Little Miss Muffet sat on a tuffet, eating her curds and whey.\' What was Miss Muffet doing?', ['Sleeping', 'Playing', 'Eating', 'Running'], 3),
    q('Reading Comprehension', 'easy', 'Tom wears a coat and scarf. What is the weather probably like?', 'Tom wears a coat and scarf. What is the weather probably like?', ['Hot', 'Rainy', 'Cold', 'Sunny'], 3),
    q('Reading Comprehension', 'easy', 'Sue has a candle because the lights went out. What happened?', 'Sue has a candle because the lights went out. What happened?', ['She is having a party', 'The power went out', 'She is decorating', 'She is cooking'], 2),
    q('Reading Comprehension', 'easy', 'The boy yawns and rubs his eyes. He is probably ___.', 'The boy yawns and rubs his eyes. He is probably ___.', ['Hungry', 'Angry', 'Sleepy', 'Excited'], 3),
    q('Reading Comprehension', 'easy', 'Anna smiles and jumps up and down. She is probably ___.', 'Anna smiles and jumps up and down. She is probably ___.', ['Sad', 'Angry', 'Scared', 'Happy'], 4),
    q('Reading Comprehension', 'easy', 'The children run to get umbrellas. What is the weather?', 'The children run to get umbrellas. What is the weather?', ['Sunny', 'Windy', 'Rainy', 'Snowy'], 3),
    q('Reading Comprehension', 'easy', 'There is cake and balloons. What event is happening?', 'There is cake and balloons. What event is happening?', ['Graduation', 'Birthday party', 'Wedding', 'Funeral'], 2),
    q('Reading Comprehension', 'easy', 'The teacher says \'Open your books.\' What should students do?', 'The teacher says \'Open your books.\' What should students do?', ['Stand up', 'Close books', 'Open their books', 'Start writing'], 3),
    q('Reading Comprehension', 'easy', '\'First I wash my hands, then I eat.\' When does she eat?', '\'First I wash my hands, then I eat.\' When does she eat?', ['Before washing', 'After washing hands', 'At the same time', 'Not mentioned'], 2),
    q('Reading Comprehension', 'easy', 'The cat is by the fish bowl. The cat licks its lips. What might happen?', 'The cat is by the fish bowl. The cat licks its lips. What might happen?', ['The cat will sleep', 'The cat will drink water', 'The cat wants to eat the fish', 'The cat will play'], 3),
    q('Reading Comprehension', 'easy', 'Dad puts on his coat and picks up his keys. He is going to ___.', 'Dad puts on his coat and picks up his keys. He is going to ___.', ['Sleep', 'Cook', 'Go outside', 'Watch TV'], 3),
    q('Reading Comprehension', 'easy', '\'She is as busy as a bee.\' This means she is very ___.', '\'She is as busy as a bee.\' This means she is very ___.', ['Sweet', 'Small', 'Hardworking', 'Quiet'], 3),
    q('Reading Comprehension', 'easy', 'The ice cream melted in the sun. What caused this?', 'The ice cream melted in the sun. What caused this?', ['Cold weather', 'Rain', 'Heat from the sun', 'Wind'], 3),
    q('Reading Comprehension', 'easy', '\'The early bird catches the worm.\' This means if you ___.', '\'The early bird catches the worm.\' This means if you ___.', ['Wake up late you get more food', 'Wake up early you have an advantage', 'Birds like worms', 'Go to bed early'], 2),
    q('Reading Comprehension', 'easy', '\'It\'s raining cats and dogs.\' What does this expression mean?', '\'It\'s raining cats and dogs.\' What does this expression mean?', ['Animals are falling from sky', 'It\'s raining very heavily', 'Cats and dogs are playing', 'It\'s raining lightly'], 2),
    q('Reading Comprehension', 'easy', 'A girl is sitting alone and crying. She is probably ___.', 'A girl is sitting alone and crying. She is probably ___.', ['Happy', 'Excited', 'Upset or sad', 'Hungry'], 3),

    // ── Phonics & Spelling ──
    q('Phonics & Spelling', 'easy', 'Which word starts with the letter \'B\'?', 'Which word starts with the letter \'B\'?', ['Apple', 'Cat', 'Ball', 'Dog'], 3),
    q('Phonics & Spelling', 'easy', 'Which word starts with the letter \'C\'?', 'Which word starts with the letter \'C\'?', ['Bag', 'Cat', 'Egg', 'Dog'], 2),
    q('Phonics & Spelling', 'easy', 'Which word ends with \'-at\'?', 'Which word ends with \'-at\'?', ['Dog', 'Cat', 'Hen', 'Fox'], 2),
    q('Phonics & Spelling', 'easy', 'Which word rhymes with \'cat\'?', 'Which word rhymes with \'cat\'?', ['Dog', 'Car', 'Hat', 'Pen'], 3),
    q('Phonics & Spelling', 'easy', 'Which word rhymes with \'dog\'?', 'Which word rhymes with \'dog\'?', ['Fog', 'Cat', 'Hen', 'Ball'], 1),
    q('Phonics & Spelling', 'easy', 'Which word rhymes with \'sun\'?', 'Which word rhymes with \'sun\'?', ['Moon', 'Star', 'Run', 'Sky'], 3),
    q('Phonics & Spelling', 'easy', 'Which word rhymes with \'hop\'?', 'Which word rhymes with \'hop\'?', ['Help', 'Hope', 'Shop', 'Hat'], 3),
    q('Phonics & Spelling', 'easy', 'Which word rhymes with \'fish\'?', 'Which word rhymes with \'fish\'?', ['Dish', 'Book', 'Tree', 'Bird'], 1),
    q('Phonics & Spelling', 'easy', 'Which word rhymes with \'cake\'?', 'Which word rhymes with \'cake\'?', ['Take', 'Cook', 'Bird', 'Ball'], 1),
    q('Phonics & Spelling', 'easy', 'Which word rhymes with \'night\'?', 'Which word rhymes with \'night\'?', ['Day', 'Star', 'Light', 'Moon'], 3),
    q('Phonics & Spelling', 'easy', 'What is the correct spelling of the color?', 'What is the correct spelling of the color?', ['Bloo', 'Blou', 'Blue', 'Bluw'], 3),
    q('Phonics & Spelling', 'easy', 'What is the correct spelling?', 'What is the correct spelling?', ['Grene', 'Green', 'Grean', 'Gren'], 2),
    q('Phonics & Spelling', 'easy', 'What is the correct spelling?', 'What is the correct spelling?', ['Yello', 'Yellw', 'Yelow', 'Yellow'], 4),
    q('Phonics & Spelling', 'easy', 'What is the correct spelling?', 'What is the correct spelling?', ['Redd', 'Red', 'Rad', 'Rede'], 2),
    q('Phonics & Spelling', 'easy', 'What is the correct spelling?', 'What is the correct spelling?', ['Oraneg', 'Orenge', 'Orange', 'Oring'], 3),
    q('Phonics & Spelling', 'easy', 'Which letter comes after \'D\' in the alphabet?', 'Which letter comes after \'D\' in the alphabet?', ['C', 'E', 'F', 'B'], 2),
    q('Phonics & Spelling', 'easy', 'Which letter comes before \'G\' in the alphabet?', 'Which letter comes before \'G\' in the alphabet?', ['F', 'H', 'I', 'E'], 1),
    q('Phonics & Spelling', 'easy', 'How many vowels are in the word \'apple\'?', 'How many vowels are in the word \'apple\'?', ['1', '2', '3', '4'], 2),
    q('Phonics & Spelling', 'easy', 'What are the vowels in English?', 'What are the vowels in English?', ['a, b, c, d, e', 'a, e, i, o, u', 'b, c, d, f, g', 'a, e, i, o, y'], 2),
    q('Phonics & Spelling', 'easy', 'Which word has a silent letter?', 'Which word has a silent letter?', ['Cat', 'Dog', 'Knee', 'Run'], 3),
    q('Phonics & Spelling', 'easy', 'What sound does \'ph\' make?', 'What sound does \'ph\' make?', ['P sound', 'H sound', 'F sound', 'B sound'], 3),
    q('Phonics & Spelling', 'easy', 'What does \'ch\' sound like in \'chair\'?', 'What does \'ch\' sound like in \'chair\'?', ['K', 'Sh', 'Ch', 'S'], 3),
    q('Phonics & Spelling', 'easy', 'What does \'sh\' sound like in \'ship\'?', 'What does \'sh\' sound like in \'ship\'?', ['S', 'H', 'Sh', 'Ch'], 3),
    q('Phonics & Spelling', 'easy', 'Which word has the long \'A\' sound?', 'Which word has the long \'A\' sound?', ['Cat', 'Apple', 'Cake', 'Ant'], 3),
    q('Phonics & Spelling', 'easy', 'Which word has the short \'I\' sound?', 'Which word has the short \'I\' sound?', ['Ice', 'Bite', 'Sit', 'Pine'], 3),
    q('Phonics & Spelling', 'easy', 'How many syllables are in \'elephant\'?', 'How many syllables are in \'elephant\'?', ['2', '3', '4', '5'], 2),
    q('Phonics & Spelling', 'easy', 'How many syllables are in \'butterfly\'?', 'How many syllables are in \'butterfly\'?', ['2', '3', '4', '5'], 2),
    q('Phonics & Spelling', 'easy', 'How many syllables are in \'cat\'?', 'How many syllables are in \'cat\'?', ['1', '2', '3', '4'], 1),
    q('Phonics & Spelling', 'easy', 'Which word has double letters?', 'Which word has double letters?', ['Cat', 'Dog', 'Ball', 'Fish'], 3),
    q('Phonics & Spelling', 'easy', 'Which word is correctly capitalized at the start?', 'Which word is correctly capitalized at the start?', ['apple', 'Apple', 'APPLE', 'aPPLE'], 2),
    q('Phonics & Spelling', 'easy', 'What is the correct spelling of the number ten?', 'What is the correct spelling of the number ten?', ['Tne', 'Tin', 'Ten', 'Tan'], 3),
    q('Phonics & Spelling', 'easy', 'What is the correct spelling?', 'What is the correct spelling?', ['Frend', 'Frind', 'Freind', 'Friend'], 4),
    q('Phonics & Spelling', 'easy', 'What is the correct spelling?', 'What is the correct spelling?', ['Scool', 'School', 'Schol', 'Skool'], 2),
    q('Phonics & Spelling', 'easy', 'What is the correct spelling?', 'What is the correct spelling?', ['Haus', 'Hows', 'House', 'Howse'], 3),
    q('Phonics & Spelling', 'easy', 'What is the correct spelling?', 'What is the correct spelling?', ['Tabel', 'Table', 'Tabell', 'Tabble'], 2),

    // ── Science & Nature ──
    q('Science & Nature', 'easy', 'What do plants need to grow?', 'What do plants need to grow?', ['Only water', 'Only sunlight', 'Sunlight, water, and air', 'Only soil'], 3),
    q('Science & Nature', 'easy', 'What do we breathe to survive?', 'What do we breathe to survive?', ['Carbon dioxide', 'Oxygen', 'Nitrogen', 'Steam'], 2),
    q('Science & Nature', 'easy', 'What is the center of our solar system?', 'What is the center of our solar system?', ['Earth', 'Moon', 'Mars', 'Sun'], 4),
    q('Science & Nature', 'easy', 'How many planets are in our solar system?', 'How many planets are in our solar system?', ['7', '8', '9', '10'], 2),
    q('Science & Nature', 'easy', 'What is the closest planet to Earth?', 'What is the closest planet to Earth?', ['Mars', 'Venus', 'Jupiter', 'Mercury'], 2),
    q('Science & Nature', 'easy', 'What is the largest planet?', 'What is the largest planet?', ['Saturn', 'Earth', 'Jupiter', 'Neptune'], 3),
    q('Science & Nature', 'easy', 'What is the biggest star closest to Earth?', 'What is the biggest star closest to Earth?', ['Moon', 'Mars', 'Sun', 'Venus'], 3),
    q('Science & Nature', 'easy', 'What is the natural satellite of Earth?', 'What is the natural satellite of Earth?', ['Sun', 'Mars', 'Moon', 'Venus'], 3),
    q('Science & Nature', 'easy', 'What do we call water that falls from the sky?', 'What do we call water that falls from the sky?', ['Fog', 'Dew', 'Rain', 'Mist'], 3),
    q('Science & Nature', 'easy', 'What state of water is ice?', 'What state of water is ice?', ['Liquid', 'Gas', 'Solid', 'Plasma'], 3),
    q('Science & Nature', 'easy', 'What state of water is steam?', 'What state of water is steam?', ['Liquid', 'Gas', 'Solid', 'Plasma'], 2),
    q('Science & Nature', 'easy', 'What is the boiling point of water?', 'What is the boiling point of water?', ['50°C', '80°C', '100°C', '120°C'], 3),
    q('Science & Nature', 'easy', 'What is the freezing point of water?', 'What is the freezing point of water?', ['0°C', '10°C', '-10°C', '5°C'], 1),
    q('Science & Nature', 'easy', 'What do we call scientists who study plants?', 'What do we call scientists who study plants?', ['Biologists', 'Geologists', 'Botanists', 'Chemists'], 3),
    q('Science & Nature', 'easy', 'What is photosynthesis?', 'What is photosynthesis?', ['How animals eat', 'How plants make food using sunlight', 'How water evaporates', 'How rocks form'], 2),
    q('Science & Nature', 'easy', 'What does a thermometer measure?', 'What does a thermometer measure?', ['Wind speed', 'Temperature', 'Rainfall', 'Air pressure'], 2),
    q('Science & Nature', 'easy', 'What is the process of water becoming vapor called?', 'What is the process of water becoming vapor called?', ['Condensation', 'Evaporation', 'Precipitation', 'Filtration'], 2),
    q('Science & Nature', 'easy', 'What are the three states of matter?', 'What are the three states of matter?', ['Hard, soft, medium', 'Solid, liquid, gas', 'Big, small, medium', 'Hot, cold, warm'], 2),
    q('Science & Nature', 'easy', 'What makes day and night on Earth?', 'What makes day and night on Earth?', ['Earth\'s rotation', 'Moon\'s movement', 'Sun\'s movement', 'Cloud movement'], 1),
    q('Science & Nature', 'easy', 'What is the process of a caterpillar becoming a butterfly?', 'What is the process of a caterpillar becoming a butterfly?', ['Hibernation', 'Migration', 'Metamorphosis', 'Evolution'], 3),
];

export const seedGrade2EnglishQuestions = async () => {
    console.log('🌱 Seeding Grade 2 English questions to Supabase...');
    console.log(`📦 Total questions to insert: ${grade2EnglishQuestions.length}`);

    // Insert in batches of 50 to avoid request size limits
    const batchSize = 50;
    let inserted = 0;
    for (let i = 0; i < grade2EnglishQuestions.length; i += batchSize) {
        const batch = grade2EnglishQuestions.slice(i, i + batchSize);
        const { error } = await supabase.from('questions').insert(batch);
        if (error) {
            console.error(`❌ Error inserting batch ${i / batchSize + 1}:`, error);
            process.exit(1);
        }
        inserted += batch.length;
        console.log(`   ✅ Inserted ${inserted}/${grade2EnglishQuestions.length}`);
    }
    console.log('✅ Successfully seeded all Grade 2 English questions!');
};

// Run directly: npx tsx src/server/seed_grade2_english.ts
seedGrade2EnglishQuestions();
